name: Update Firebase Database

on:
  push:
    branches: [ main ]  # Ou la branche que vous utilisez pour les mises à jour

jobs:
  update_database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Assurez-vous que cette version est compatible avec vos outils

      - name: Install dependencies
        run: npm install

      - name: Update Firebase Database
        run: node path/to/your/script.js
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
